/*
 * 초기 프로젝트 데이터
 * ------------------
 * 이 파일을 직접 수정해도 되고, 사이트의 Manage 버튼으로 추가/수정한 뒤
 * JSON을 내보내 백업해도 됩니다. 브라우저에서 수정한 내용은 localStorage에 저장됩니다.
 *
 * image에는 이 폴더 기준 상대 경로를 넣으세요. 예: "./assets/ovo-cover.jpg"
 */

window.ARCHIVE_SEED = [
  {
    id: "korean-garden",
    title: "Korean Garden",
    year: "2024",
    status: "Finished",
    featured: true,
    categories: ["3D 영상작업"],
    tools: ["Unreal", "C4D"],
    summary: "인천공항 미디어월을 위해 제작한 한국 정원 3D 애니메이션.",
    description: "한국의 정원과 전통 놀이, 음악, 생활 풍경을 하나의 순환형 공간 안에 구성한 대형 미디어월 영상입니다.",
    role: "3D production · environment · realtime scene",
    contribution: "정확한 담당 범위와 협업 비율 확인 필요.",
    result: "인천국제공항 대형 미디어월 상영.",
    target: "Unreal · Realtime · Media Art · 3D Generalist 지원",
    portfolioPoint: "상업 작업의 완성도, Unreal 환경 구성, 공간 연출.",
    notes: "메인 포트폴리오 1순위. 스토리보드, 최종 영상, 현장 사진 보관.",
    image: "./assets/korean-garden/cover.jpg",
    video: {
      src: "./assets/korean-garden/film.mp4",
      poster: "./assets/korean-garden/video-poster.jpg",
      title: "Korean Garden — Final Film"
    },
    gallery: [
      { src: "./assets/korean-garden/airport-mockup.jpg", title: "Airport Display Mockup", wide: true },
      { src: "./assets/korean-garden/installation-01.jpg", title: "On-site Installation 01" },
      { src: "./assets/korean-garden/installation-02.jpg", title: "On-site Installation 02" }
    ],
    storyboard: [
      { src: "./assets/korean-garden/storyboard-01.png", title: "Storyboard 01–02" },
      { src: "./assets/korean-garden/storyboard-02.png", title: "Storyboard 03–04" },
      { src: "./assets/korean-garden/storyboard-03.png", title: "Storyboard 05–06" }
    ],
    palette: 0
  },
  {
    id: "ovo",
    title: "OVO",
    year: "2026",
    status: "Finished",
    featured: true,
    categories: ["XR/VR"],
    tools: ["visionOS", "C4D"],
    summary: "visionOS 환경을 위한 spatial 3D 경험.",
    description: "공간 컴퓨팅 환경 안에서 3D 오브젝트와 사용자 경험을 연결한 프로젝트입니다.",
    role: "Spatial 3D · asset production · visual direction",
    contribution: "세부 기여도와 개발 협업 범위를 추가로 기록하세요.",
    result: "visionOS / App Store 맥락으로 정리할 수 있는 결과물.",
    target: "XR · Spatial Computing · visionOS · 3D Product 지원",
    portfolioPoint: "평면 화면이 아닌 공간 안에서의 크기, 거리, 인터랙션 설계.",
    notes: "실기기 화면과 제작 과정을 함께 정리.",
    image: "",
    palette: 1
  },
  {
    id: "techmap-unity",
    title: "TechMap",
    year: "2026",
    status: "In Progress",
    featured: true,
    categories: ["전시"],
    tools: ["Unity"],
    summary: "Unity 기반 인터랙션 전시 프로젝트.",
    description: "전시 환경에서 실시간 인터랙션이 작동하도록 설계하고 구현한 작업입니다. 전시 맥락과 관객 동선을 중심으로 기록합니다.",
    role: "Unity realtime · interaction · exhibition content",
    contribution: "인터랙션 설계, 구현, 현장 세팅 중 담당 범위를 구체화하세요.",
    result: "전시 기록 영상과 현장 사진 추가 예정.",
    target: "Creative Tech · Unity · Interactive Exhibition · Media Art 지원",
    portfolioPoint: "실제 공간에서 작동하는 인터랙션과 현장 대응 경험.",
    notes: "설치도, 사용자 흐름, 기술 구성도를 남기기.",
    image: "",
    palette: 2
  },
  {
    id: "c6",
    title: "C6",
    year: "2026",
    status: "In Progress",
    featured: false,
    categories: ["XR/VR"],
    tools: ["visionOS"],
    summary: "리서치와 협업 과정이 포함된 visionOS 클라이언트 프로젝트.",
    description: "클라이언트 요구와 공간 컴퓨팅 환경을 연결한 협업 프로젝트입니다.",
    role: "Research · collaboration · spatial asset support",
    contribution: "3D가 실제 결과물에 포함된 범위에 따라 비중 조정 필요.",
    result: "공개 가능 범위와 최종 산출물 확인 필요.",
    target: "XR Product · Client Collaboration · Spatial Design 지원",
    portfolioPoint: "리서치에서 결과물까지의 협업 과정.",
    notes: "NDA 및 공개 범위 확인. 메인/서브 비중은 결과물 확인 뒤 결정.",
    image: "",
    palette: 3
  },
  {
    id: "blender-personal-study",
    title: "Blender Personal Study",
    year: "2026",
    status: "In Progress",
    featured: true,
    categories: ["스터디"],
    tools: ["Blender"],
    summary: "모델링부터 라이팅과 렌더까지 이어지는 개인 3D 연구.",
    description: "개인적인 시각 언어를 개발하면서 전체 3D 제작 파이프라인을 점검하는 프로젝트입니다.",
    role: "Modeling · UV · material · lighting · render",
    contribution: "개인 작업 100%.",
    result: "완성 렌더와 단계별 breakdown 추가 예정.",
    target: "3D Generalist · CGI Artist · Product Visual 지원",
    portfolioPoint: "한 사람이 처음부터 끝까지 완성한 제작 역량.",
    notes: "과정보다 최종 퀄리티 우선. 와이어프레임/UV/재질은 보조로.",
    image: "",
    palette: 4
  },
  {
    id: "hasou",
    title: "HASOU",
    year: "2026",
    status: "In Progress",
    featured: false,
    categories: ["브랜딩"],
    tools: ["C4D"],
    summary: "AI와 3D를 오가며 구축한 비주얼 디렉션 프로젝트.",
    description: "제품, 에디토리얼, 공간 이미지를 하나의 시각 언어로 연결하는 실험입니다.",
    role: "AI visual · art direction · image curation",
    contribution: "개인 작업 100%.",
    result: "일관된 시리즈와 제작 방식 정리 예정.",
    target: "AI 활용 · Brand Visual · Creative Direction 지원",
    portfolioPoint: "생성 결과 자체보다 디렉션 기준과 선택의 일관성.",
    notes: "프롬프트 나열보다 최종 아트 디렉션과 편집 판단을 보여주기.",
    image: "",
    palette: 5
  },
  {
    id: "stockholm-nft-exhibition",
    title: "Stockholm NFT Exhibition",
    year: "2023",
    status: "Finished",
    featured: false,
    categories: ["전시"],
    tools: ["C4D"],
    summary: "물리 작품을 스캔하고 애니메이션으로 확장한 전시 작업.",
    description: "실물 작품을 3D 스캔한 뒤 Cinema 4D 애니메이션으로 전환해 전시한 프로젝트입니다.",
    role: "3D scan · Cinema 4D · animation · exhibition output",
    contribution: "스캔부터 애니메이션, 전시 출력까지의 담당 범위를 보강하세요.",
    result: "Stockholm NFT Exhibition 전시.",
    target: "Media Art · Exhibition · Experimental 3D 지원",
    portfolioPoint: "Physical → Scan → 3D Animation → Exhibition으로 이어지는 변환 과정.",
    notes: "실물 원본과 최종 전시 이미지를 한 흐름으로 배치.",
    image: "",
    palette: 6
  },
  {
    id: "visionos-competition",
    title: "visionOS Competition",
    year: "2026",
    status: "Finished",
    featured: false,
    categories: ["XR/VR"],
    tools: ["visionOS"],
    summary: "공간 경험과 3D 에셋을 결합한 visionOS 경진대회 작업.",
    description: "visionOS를 전제로 공간 경험을 설계하고 필요한 3D 에셋을 제작한 팀 프로젝트입니다.",
    role: "3D assets · spatial experience",
    contribution: "팀 구성과 개인 담당 범위, 수상 결과를 정확히 추가하세요.",
    result: "경진대회 결과 및 수상 내역 확인 필요.",
    target: "XR · visionOS · Spatial Experience 지원",
    portfolioPoint: "짧은 기간 안에 공간 제품 경험을 만든 과정과 결과.",
    notes: "정확한 대회명, 날짜, 수상명 업데이트.",
    image: "",
    palette: 7
  },
  {
    id: "whipped-anamorphic",
    title: "WHIPPED",
    year: "2026",
    status: "In Progress",
    featured: false,
    categories: ["3D 영상작업"],
    tools: ["C4D"],
    summary: "제품을 위한 anamorphic 3D visual study.",
    description: "제품 광고 맥락에서 아나모픽 공간감과 모션을 실험한 개인 작업입니다.",
    role: "Product visual · anamorphic · motion",
    contribution: "개인 작업 100%.",
    result: "짧은 루프 영상과 대표 스틸 완성 예정.",
    target: "Advertising · Brand Content · 3D Motion 지원",
    portfolioPoint: "제품 연출, C4D/Octane 렌더, 아나모픽 효과.",
    notes: "1–2일 안에 마감 가능한 범위만 진행. Selected Work 한 페이지 후보.",
    image: "",
    palette: 8
  },
  {
    id: "boseong-black-tea",
    title: "Boseong Black Tea",
    year: "2024",
    status: "Finished",
    featured: false,
    categories: ["3D 영상작업"],
    tools: ["C4D"],
    summary: "제품 중심의 상업 3D 비주얼 작업.",
    description: "보성홍차 관련 3D 결과물. 캠페인 맥락과 공개 가능한 역할을 추가로 기록하세요.",
    role: "확인 필요.",
    contribution: "확인 필요.",
    result: "최종 사용처와 결과 이미지 추가 필요.",
    target: "Product Visual · Commercial CGI 지원",
    portfolioPoint: "제품 표현과 상업 비주얼 완성도.",
    notes: "Selected Works 후보. 정확한 연도와 역할 확인.",
    image: "",
    palette: 9
  },
  {
    id: "c4-character",
    title: "C4 Character",
    year: "2024",
    status: "Finished",
    featured: false,
    categories: ["캐릭터"],
    tools: ["C4D"],
    summary: "캐릭터를 중심으로 한 3D 제작 작업.",
    description: "C4 캐릭터 프로젝트. 캐릭터 제작 범위와 최종 활용처를 보강하세요.",
    role: "확인 필요.",
    contribution: "확인 필요.",
    result: "최종 결과와 공개 가능 자료 확인 필요.",
    target: "Character · 3D Content · Commercial CGI 지원",
    portfolioPoint: "캐릭터 표현과 스타일 적응력.",
    notes: "Selected Works 후보. 프로젝트 공식명 확인.",
    image: "",
    palette: 10
  },
  {
    id: "saatchi",
    title: "Saatchi",
    year: "2023",
    status: "Archived",
    featured: false,
    categories: ["전시"],
    tools: ["C4D"],
    summary: "아트 프로젝트 아카이브 항목.",
    description: "현재 대화에 세부 정보가 없어 프로젝트 맥락을 추후 보완해야 합니다.",
    role: "확인 필요.",
    contribution: "확인 필요.",
    result: "확인 필요.",
    target: "Art · Experimental Visual 지원 여부 검토",
    portfolioPoint: "다른 작업과 구별되는 실험성과 시각 언어를 확인.",
    notes: "Selected Works 후보. 공식명, 연도, 이미지, 역할 모두 확인.",
    image: "",
    palette: 11
  },
  {
    id: "traditional-architecture-study",
    title: "Traditional Architecture Study",
    year: "2024",
    status: "Archived",
    featured: false,
    categories: ["스터디"],
    tools: ["C4D", "Unreal"],
    summary: "전통 건축 에셋을 활용한 environment·lighting 연구.",
    description: "완성을 의무로 두지 않고 Unreal 라이팅과 환경 연출을 다시 연습할 때 활용하는 아카이브 에셋입니다.",
    role: "Environment study · lighting test",
    contribution: "개인 작업 100%.",
    result: "낮 / 황혼 / 밤 라이팅 테스트가 잘 나올 경우 Selected Work로 전환.",
    target: "Environment · Unreal Lighting 역량 보완용",
    portfolioPoint: "기존 메인 작업과 중복되므로 결과 퀄리티가 높을 때만 사용.",
    notes: "완성 의무 없음. 연습용 asset으로 유지.",
    image: "",
    palette: 12
  }
];
